import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChakraProvidersWrapper } from '../components/providers/ChakraProvidersWrapper';
import ReduxProvider from "@/components/providers/ReduxProvider";
import AuthorizationProvider from "@/components/providers/AuthorizationProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sistema de Presupuestos - Mat_dweb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <ChakraProvidersWrapper>
            <AuthorizationProvider>
              {children}
            </AuthorizationProvider>
          </ChakraProvidersWrapper>
        </body>
      </html>
    </ReduxProvider>
  );
}
